framework:
    default_locale: en
    translator:
        paths:
            - '%kernel.project_dir%/src/Presentation/Shared/Translations'
            - '%kernel.project_dir%/src/Presentation/Translations'
        fallbacks:
            - en
            - pl
            - ru
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
