doctrine:
  orm:
    mappings:
      User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/User/Doctrine/Orm/Mapping'
        prefix: 'App\Domain\User\Entity'
        alias: User
