http:
  services:
    api-service:
      loadBalancer:
        servers:
          - url: "http://api_caddy"

  routers:
    traefik-dashboard:
      tls: { }
      entryPoints:
        - https
      rule: Host(`traefik.needrise.localhost`)
      service: api@internal

    api:
      tls: { }
      entryPoints:
        - https
      rule: Host(`oauth.needrise.localhost`)
      service: api-service

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/localhost.crt
        keyFile: /etc/certs/localhost.key
  certificates:
    - certFile: /etc/certs/localhost.crt
      keyFile: /etc/certs/localhost.key
